<option value="Devoice">Devoice</option>
<option value="Engaged">Engaged</option>
<option value="In a civil partnership">In a civil partnership</option>
<option value="In a domestic partnership">In a domestic partnership</option>
<option value="In a relationship">In a relationship</option>
<option value="In an open relationship">In an open relationship</option>
<option value="It's complicated">It's complicated</option>
<option value="Married">Married</option>
<option value="Separated">Separated</option>
<option value="Single">Single</option>
<option value="Widowed">Widowed</option>